config/routes.rb
Rails.application.routes.draw do
  get 'flames/jindex'

  get 'flames/rindex'

  root 'home#index'
  get 'home/portfolio' => 'home#portfolio'
  get 'home/about'  => 'home#about'
  get 'home/blog' => 'home#blog'
  get 'home/puzzle' => 'home#puzzle'
  get 'home/contact' => 'home#contact'
  get 'astra' => 'home#astra'
  resources "contacts", only: [:new, :create]
  

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "raviandkanth@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/flames_controller.rb
class FlamesController < ApplicationController
  def jindex

  end

  def rindex

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def portfolio
  end

  def about
  end

  def blog
  end

  def puzzle
  end

  def astra
    redirect_to "https://docs.google.com/spreadsheets/d/1YoDLnlBxtfyaL-YU1-lkfsMXLDfiXRiWg_9_N5n4xqQ/edit#gid=0"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/flames_helper.rb
module FlamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  # def nav_items
  #   nav_item("Home", root_path, action_name == "index") +
  #     nav_item("Portfolio", home_portfolio_path, action_name == "portfolio") +
  #     nav_item("About", home_about_path, action_name == "about") +
  #     nav_item("Blog", home_blog_path, action_name == "blog") +
  #     nav_item("Puzzles", home_puzzle_path, action_name == "puzzle") :blog, :puzzle,
  # end

  def nav_items
    [:index, :portfolio, :about, :new].collect do |actn|
      nav_item(nav_link_text(actn), nav_link_path(actn), action_name.to_sym == actn)
    end.reduce(&:+)
  end

  def nav_link_text(actn)
    {index: "Home", portfolio: "Portfolio", about: "About", blog: "Blog", puzzle: "Puzzles",
     new: "Contact"}[actn]
  end

  def nav_link_path(actn)
    {index: root_path, portfolio: home_portfolio_path, about: home_about_path, blog: home_blog_path,
     puzzle: home_puzzle_path, new: new_contact_path}[actn]
  end

  def nav_item(txt, link, active)
    content_tag(:li, class: (active ? "active" : "")) do
      link_to txt, link
    end
  end
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div align="center">
    <div class="col-md-offset-2 col-md-8">
    <h3>Send a message to me or call me at 91-7386316739</h3>

    <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
        </br>
        <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/flames/jindex.html.erb
<div class="container">
  <div class="page-header"><h1>Welcome to FLAMES game</h1></div>


  <form class="form-horizontal" role="form">
    <div class="form-group">
      <label for="nameone" class="col-sm-3 control-label">Your Name</label>
      <div class="col-sm-6">
        <input type="text" class="form-control" id="nameone" placeholder="Your Name">
      </div>
    </div>
    <div class="form-group">
      <label for="nametwo" class="col-sm-3 control-label">Crush Name</label>
      <div class="col-sm-6">
        <input type="text" class="form-control" id="nametwo" placeholder="Name Of Your Crush">
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-4">
        <button type="submit" class="btn btn-danger btn-lg btn-block" onclick="rajan(); return false;">Calculate FLAMES</button>
      </div>
    </div>
  </form>
  <hr/>
  <div class="row">
    <div class="col-xs-12"><h1 id="output"></h1></div>
  </div>
</div>

app/views/flames/rindex.html.erb
   <div class="container">
      <div class="page-header"><h1>Welcome to FLAMES game</h1></div>
    

      <form class="form-horizontal" role="form">
        <div class="form-group">
          <label for="nameone" class="col-sm-3 control-label">Your Name</label>
          <div class="col-sm-6">
            <input type="text" class="form-control" id="nameone" placeholder="Your Name">
          </div>
        </div>
        <div class="form-group">
          <label for="nametwo" class="col-sm-3 control-label">Crush Name</label>
          <div class="col-sm-6">
            <input type="text" class="form-control" id="nametwo" placeholder="Name Of Your Crush">
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-4">
            <button type="submit" class="btn btn-danger btn-lg btn-block" >Calculate FLAMES</button>
          </div>
        </div>
      </form>
      <hr/>
      <div class="row">
        <div class="col-xs-12"><h1 id="output"><%= params[:nameone] %></h1></div>
      </div>

    </div>

app/views/home/about.html.erb
<div class="container">
  <h1>About me</h1>
  <div class="row">
    <div class="col-md-12">

      <p>
      I am part of a  <a href="http://www.codeastra.com/">bootcamp</a> since November 17th. The bootcamp, called CodeAstra, is focussed on Rails, JQuery, Javascript, CSS and HTML. You can find an updated list of projects at the <%= link_to "portfolio", home_portfolio_path %>. You can expect a lot more projects by the end of 3 months. Our bootcamp has 70 hour work weeks.</p> 

      <p>
      I have been a team leader for several multi disciplinary projects. I will briefly list a summary of all the multidisciplinary projects I have led.

      <ul>
        <li>I was the team leader for the team which set up a lab in India which is planned, maintained and used by the students of IIT Madras. The lab had a budget of 80lakhs. Over 150 students actively participated in the lab. Some of the visitors to our lab include Carlos Ghoshn (global CEO of Renault Nissan), Lynn Evans(Director of Large Hedron Collider) and R. Chidambaram (scientific advisor to the Prime Minister) etc. </li>
        <li>I led a multidisciplinary team which built a completely automated quadrotor which can navigate indoors. We participated in the 2010 chapter of International Aerial Robotics competition in Puerto Rico.</li>
        <li>I was the manager and mentor for 9 large multi-disciplinary projects which were conducted as a part of Golden Jubilee celebrations in IIT Madras in 2008</li>
        <li>I was the first person to create a trend in IIT Madras by initiating what are called Spirit of Engineering projects in my freshmen year. This formed basis for all my other roles</li>
      </ul>
      </p> 

      <p>
        I have 3000 hours of experience of yoga. This lets me drive myself to the fullest without the possibility of getting "burnt out". For a detailed explanation on this  you can have a conversation with me.
      </p>


    </div>
  </div>
</div>

app/views/home/blog.html.erb
<div class= "container">
  <h1>Home#blog</h1>
</div>

app/views/home/contact.html.erb
<div class= "container">
  <h1>Home#contact</h1>
</div>

app/views/home/index.html.erb
<div class= 'container' id="hometopcont">
  <div class= "row">
    <div class = "col-md-6" id = "texttop"><h2>I am a full stack developer who can build complex web applications for you</h2></div>
    <div class = "col-md-6" id="face"><%= image_tag("ravi.png") %></div>
  </div>
</div>

<div class="container" id = "homebottomcont">
  <div class="row">
    <div class="col-md-12">
      <p>
      My name is Ravikanth Andhavarapu.  I am an alumnus of IIT Madras. I bring a combination of three skills which you won't find anywhere else. You may be able to find the skills individually but you wont be able to find the combination anywhere else.
      <ul>
        <li>I am a full stack developer with expertise in Rails, JQuery, Javascript, CSS and HTML</li>
        <li>I have project management experience in handling various multi-disciplinary projects. The teams I led varied from 5 members to over 100 members.</li>
        <li>I can drive myself to the fullest without getting "burnt out". Because of the 3000 hours of effort I put in the past 4 years I can be both highly driven and balanced at the same time. </li>
      </ul>
      </p>
      To know more about my projects please visit my <%= link_to "portfolio", home_portfolio_path %>. To know more about me please <%= link_to "click here", home_about_path %>
      <p>
    </div>
  </div>
</div>
	
	

app/views/home/portfolio.html.erb
<div class="container" id="portfolio">
   <div class="page-header middle"><h2>Projects which potray my web development and project management experience</h2></div>

  I have experience in three different types of projects viz. web development, technical and semi-technical projects. I am listing down all the different projects I have done. I was the team leader for all the projects which are not in the field of web development.
  
  <h1 class = "middle">Web Development Projects</h1>
  <ul>
    <li><a href="https://github.com/helloravi">Git hub profile </a></li>
    <li><a href="https://bitbucket.org/helloravi">Bitbucket profile</a>(Almost everything here is private)</li>
  </ul>

  <h3 class = "middle">Project 1: Rhythm tapper</h3>
  <p>Rhythm tapper lets you train to the tune of the given music. It displays how accurately you are tapping to the music. The backend and the visualizer on the front end were written by me. The rest of the UI was written by Promod. The idea was concieved by Varun Saurya. The application was fine tuned to match the music by Sandeep. We plan to develop the application further.
  <a href="http://rhythmatic.herokuapp.com">Click here</a> to check out our music application</p>
  <p>
    <%= image_tag("rhythmscreenshot.png", :class=>"portfolio")%>
  </p>

   <h3 class = "middle">Project 2: Twitter Clone</h3>
  <p>As a precursor to learning web development in Rails. I made a twitter clone based on Michael Hartl Rails tutorial.You can find the link to the  <a href="https://ravihartl.herokuapp.com/">project here</a>.</p>
    <p>
    <%= image_tag("twitclone.png", :class=>"portfolio")%>
  </p>

  <h3 class = "middle">Project 3: FLAMES game in Javascript</h3>
  <p><%= link_to "Flames game", flames_jindex_path %> is a javascript based game deployed on rails. It takes two names and gives out the relationship based on an algorithm. As you can guess it is a fun game. </p>
  <p>
    <%= image_tag("flames.png", :class=>"portfolio") %>
  </p>


 


  <h1 class = "middle">Technical Project Management</h1>
  <h3 class = "middle">Project 1: Development of an autonomous aerial vehicle using Laser range finder</h3>
  <p>I was the team lead for a multidisciplinary team which worked on creating a quadrotor. The aim was to make the quadrotor move indoor with map creating intelligence. The flying vehicle is completely autonomous.</p>
  <div style="text-align:center;">
  <iframe style="margin:auto;" width="900" height="675" src="//www.youtube.com/embed/xLhBeVuuon0" frameborder="0" allowfullscreen></iframe>
  </div>
  <h3 class = "middle">Project 2: Unmanned fixed wing airplane</h3>
  <p>This project is the first flying project of IIT Madras. It was covered by NDTV prime time news.</p>
  <%= image_tag("wanttofly.jpg", :class=>"portfolio") %>

  
  <h1 class = "middle">Semi-Technical Project Management</h1>
  <h3 class = "middle">Project 1: Centre For Innovation(CFI)</h3>
  <p>I was the student in charge of setting up the first lab of the country which is entirely managed by students. The following picture was taken during the visit of Mr. Carlos Ghoshn(global CEO of Renault Nissan) to CFI</p>
  <%= image_tag("1carlosghoshn.jpg", :class=>"portfolio") %>

  <h3 class = "middle">Project 2: Manager and mentor for over 9 projects</h3>
  <p>I was the student manager and mentor for all the projects in the video which were done after 2008.</p>
  <div style="text-align:center;">
  <iframe style="margin:auto;" width="900" height="625" src="//www.youtube.com/embed/3o2sgBbkvpY" frameborder="0" allowfullscreen></iframe>
  </div>

  <h2>Watch out for updates on this space!</h2>




</div>

app/views/home/puzzle.html.erb
<div class= "container">
  <h1>Home#puzzle</h1>
</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ravikanth | Full Stack Web Developer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



    <nav role="navigation" class="navbar navbar-default navbar-fixed-top">
      <div class="container"> 
        <%= link_to "Ravikanth Andhavarapu", root_path, class: "navbar-brand", id: "myname" %>
        <button class="navbar-toggle" data-toggle="collapse" data-target = "#navbarCollapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div id="navbarCollapse" class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
                <%= nav_items %>
            </ul>
        </div>

      </div>
    </nav>

<div class="maincontent">

<%= yield %>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54776154-2', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>